const sampleListings = [
  {
    title: "Beachfront Paradise",
    description: "Wake up to the sound of waves in this oceanfront house in Malibu.",
    image: "https://source.unsplash.com/800x600/?beach,malibu",
    price: 3200,
    location: "Malibu",
    country: "USA",
    category: "beach",
  },
  {
    title: "Cozy Countryside Cottage",
    description: "Escape the city in this peaceful countryside retreat.",
    image: "https://source.unsplash.com/800x600/?countryside,cottage",
    price: 1500,
    location: "Vermont",
    country: "USA",
    category: "countryside",
  },
  {
    title: "Luxury Poolside Villa",
    description: "Soak in the sun by your private pool in this modern villa.",
    image: "https://source.unsplash.com/800x600/?villa,pool",
    price: 4000,
    location: "Miami",
    country: "USA",
    category: "pools",
  },
  {
    title: "Lakeside A-frame Getaway",
    description: "Enjoy kayaking and bonfires by the lake in this cozy A-frame cabin.",
    image: "https://source.unsplash.com/800x600/?lake,cabin",
    price: 1800,
    location: "Lake Tahoe",
    country: "USA",
    category: "lakes",
  },
  {
    title: "Tropical Treehouse Retreat",
    description: "Live among the treetops in a serene tropical setting.",
    image: "https://source.unsplash.com/800x600/?treehouse,tropical",
    price: 1300,
    location: "Bali",
    country: "Indonesia",
    category: "tropical",
  },
  {
    title: "Icelandic Arctic Dome",
    description: "Sleep under the Northern Lights in a warm Arctic dome.",
    image: "https://source.unsplash.com/800x600/?arctic,dome",
    price: 2900,
    location: "Reykjavík",
    country: "Iceland",
    category: "arctic",
  },
  {
    title: "Camping Under the Stars",
    description: "Unplug and reconnect with nature at this forest campsite.",
    image: "https://source.unsplash.com/800x600/?camping,forest",
    price: 700,
    location: "Yosemite",
    country: "USA",
    category: "camping",
  },
  {
    title: "Rustic Farmhouse Experience",
    description: "Enjoy life on the farm with fresh eggs and open skies.",
    image: "https://source.unsplash.com/800x600/?farmhouse,barn",
    price: 1100,
    location: "Iowa",
    country: "USA",
    category: "farm",
  },
  {
    title: "Skyline Views Apartment",
    description: "Modern apartment with stunning views of the city skyline.",
    image: "https://source.unsplash.com/800x600/?apartment,city-view",
    price: 2700,
    location: "New York",
    country: "USA",
    category: "amazing-views",
  },
  {
    title: "Iconic London Flat",
    description: "Stay in a classic British flat near Big Ben.",
    image: "https://source.unsplash.com/800x600/?london,flat",
    price: 2400,
    location: "London",
    country: "UK",
    category: "icons",
  },
  {
    title: "Trending Tiny Home",
    description: "Minimalist and viral – this trending tiny home is Insta-perfect.",
    image: "https://source.unsplash.com/800x600/?tinyhome,trending",
    price: 1300,
    location: "Portland",
    country: "USA",
    category: "trending",
  },
  {
    title: "Charming Bed & Breakfast",
    description: "Start your day with a homemade breakfast in this historic B&B.",
    image: "https://source.unsplash.com/800x600/?bedandbreakfast,cozy",
    price: 900,
    location: "Savannah",
    country: "USA",
    category: "bed&breakfast",
  },
  {
    title: "Designer Rooms in Paris",
    description: "Stay in the heart of Paris in this stylish multi-room flat.",
    image: "https://source.unsplash.com/800x600/?paris,apartment",
    price: 3100,
    location: "Paris",
    country: "France",
    category: "rooms",
  }
];


module.exports = { data: sampleListings };